### ISSUE TITLE
An ability to provide custom secret for memphis creds.

### ISSUE THREAD

**Issue by valeraBr** [memphisdev/memphis-k8s#128]
An ability to provide a custom secret name with memphis-creds during helm deployment that will ensure that the values are not exposed in the install/upgrade process. 
Asked by: @madestreel

**Comment by madestreel** [comment]
@valeraBr Do you think this will be included in the release of next week?

**Comment by valeraBr** [comment]
Hi @madestreel ,
We are working on critical enhancements that should come in our next release. In case this issue will not covered up it will be released as a separate release in the first week of July.

**Comment by valeraBr** [comment]
This issue is solved in v1.1.0.
Thanks @madestreel
