### ISSUE TITLE
Can't install using flux due to duplicate key

### ISSUE THREAD

**Issue by bs1180** [memphisdev/memphis-k8s#169]
Hi,
I'm trying to install this using flux but ran into the following error:

`Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 18: mapping key "JWT_SECRET_REST_GW" already defined at line 16`

This seems to have occurred with [other charts as well](https://github.com/fluxcd/helm-controller/issues/286#issuecomment-870524258) and I think the cause is [this](https://github.com/memphisdev/memphis-k8s/blob/master/memphis/templates/memphis-creds.yaml#L13-L16) duplication of the env vars. Is it possible to remove it?

Thanks

Edit: After looking at [this open PR](https://github.com/memphisdev/memphis-k8s/pull/137), I think the refactoring there will already solve this issue 🥳

**Comment by yanivbh1** [comment]
Hey @bs1180 ,
Adding @valeraBr

**Comment by PeteMac88** [comment]
We have the same problem. When will the PR be merged? 

@faweis

**Comment by valeraBr** [comment]
Hi @bs1180 and @PeteMac88 , a new version of the helm chart was released yesterday with the fix.
