### ISSUE TITLE
Add support for automatic protocol detection for most common service meshes

### ISSUE THREAD

**Issue by PeteMac88** [memphisdev/memphis-k8s#186]
Add support for automatic protocol detection for the ports provided by the service resource for service meshes like [istio](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/) or [kong](https://docs.konghq.com/mesh/latest/policies/protocol-support-in-kong-mesh/). This can normally be done by adding the `appProtocol` field to the ports in the service or prefixing the service ports name with the protocol.

I created a PR to add the field see https://github.com/memphisdev/memphis-k8s/pull/185

**Comment by PeteMac88** [comment]
@bkochauri-memphis  Can you close the issue after the new chart version is deployed?

**Comment by bkochauri-memphis** [comment]
Hi @PeteMac88 , I am closing the issue as a new version of helm chart was released.
Thank you for your contribution to memphis project
