### ISSUE TITLE
ServiceMonitor resource endpoint spec is using port instead of targetPort

### ISSUE THREAD

**Issue by fredericve** [memphisdev/memphis-k8s#191]
According to the endpoint spec of a ServiceMonitor resource either of `port:` or `targetPort:` need to be used. In the case of `port:` it should reference the name of a port defined in the Service. In the case of `targetPort:` it should reference a port of a pod behind the service.

Since the `metrics` port is not defined in the Service it leads to a prometheus operator not finding what to monitor. In order not to expose the exporter port in the service I suggest to use `targetPort:` instead.

**Comment by valeraBr** [comment]
Hi @fredericve, 
This issue was solved in the latest release. Now you can expose metrics port in the main service using the `exporter.serviceExposed.enbaled="true"` value. 
Please update us if it doesn't meet your needs.
Thanks
